### PR TITLE
React Updated to version 16.4.2

### PR DESCRIPTION
**Pull request by rishabh-327**
React Updated to version 16.4.2

### CODE REVIEW

**Comment by imbhargav5** [comment]
@rishabh-327 Let's try updating to 16.6? I will set up continuous deployment with now.sh meanwhile.

**Comment by rishabh-327** [comment]
Ok, rest all packages works? Any other package that needs the update?

**Comment by imbhargav5** [comment]
@rishabh-327 Yeah other packages will work Rishabh. Just react-dom needs to be updated and we should be good to merge.

**Comment by imbhargav5** [comment]
Thanks @rishabh-327 ! Added you as contributor!

**Comment by rishabh-327** [comment]
Thanks !

**Pull request merged**
